### ISSUE TITLE
Consider removing the logout view

### ISSUE THREAD

**Issue by toolness** [18F/cg-django-uaa#1]
Currently the logout view is *really* trivial:

```python
def logout(request):
    django.contrib.auth.logout(request)
    return render(request, 'uaa_client/logged_out.html')
```

This is a very standard logout view.  But because `uaa_client/logged_out.html` is a template that the client has to provide, it increases the complexity of setting up the package, so we might just want to get rid of it and tell the user that they can just log the user out by consulting the Django docs on [how to log a user out](https://docs.djangoproject.com/en/1.10/topics/auth/default/#how-to-log-a-user-out).

**Comment by stvnrlly** [comment]
While it would be possible to replace the logout template, I'm not sure that it's as easy to omit the login error view, since I think that's done on the `registration/login.html` template that the UAA auth approach avoids.

In both cases, I kind of like having a template to overwrite with my own app's logout/error templates. I'm perfectly happy to overwrite the logout view, though.

**Comment by stvnrlly** [comment]
After running through the instructions in the README, I see that what I'm talking about is a little different and is already covered, so never mind me.
