### ISSUE TITLE
Consider using Django's RemoteUserBackend

### ISSUE THREAD

**Issue by stvnrlly** [18F/cg-django-uaa#30]
I noticed that Django [has a `RemoteUserBackend`](https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.backends.RemoteUserBackend) that inherits from `ModelBackend`. It's designed for handling external authentication, so it might provide some useful tools for this package.

**Comment by toolness** [comment]
Oh neat--that looks like it might be particularly useful for apps like Tock, which have some kind of cloud.gov reverse proxy sitting in between them and the internet which sets that `request.META['REMOTE_USER']` http header.

I definitely like the concept of the `create_unknown_user` attribute and the `user_can_authenticate()` method--these seem like great conventions to adopt into `cg-django-uaa`, even if we don't end up using `RemoteUserBackend`.

The one thing I'm unclear on is whether it's possible to disable the `request.META['REMOTE_USER']` lookup? Because as far as I can tell, for apps that aren't fronted by the cloud.gov reverse proxy like Tock, this could actually be a security hole...

**Comment by stvnrlly** [comment]
Yeah, looking at the documentation, it seems to be designed more for a Tock-like use case than for this type. So, switching backends likely isn't a good idea.

Still, I wonder if it'd be possible to include something like `create_unknown_user()` in this modules, `authenticate` step (which is where it happens in that backend). Sort of like what Slack does, you could be allowed to set a list of email domains (e.g. @gsa.gov) that would create an account if one doesn't exist.

Separately, if you want to use `user_can_authenticate()`: it looks like that's [included in the `ModelBackend`](https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.backends.ModelBackend.user_can_authenticate), too.

**Comment by toolness** [comment]
Definitely, that would be cool--want to submit a PR?

**Comment by toolness** [comment]
Hey @stvnrlly, is it ok to close this issue now that #31 is merged, or do you still want to look into this?

**Comment by stvnrlly** [comment]
Yep, that PR's function is why I opened this issue, so I'll close this.
